version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    # user: ${DOCKER_USER}
    networks: 
      - nextcloud_network
    depends_on:
      - nextcloud_db
      - redis
    ports:
      - 8070:80
    volumes:
      - ./data:/var/www/html
    environment:
      - TZ=${TIMEZONE}
      - REDIS_HOST=redis
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
      - nextcloud_admin_user
      - nextcloud_admin_password

  nextcloud_db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    # user: ${DOCKER_USER}
    networks: 
      - nextcloud_network
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    user: ${DOCKER_USER}
    volumes:
      - ./redis:/data  
    networks: 
      - nextcloud_network

networks:
  nextcloud_network:
    name: nextcloud-network
    driver: bridge

secrets:
  postgres_db:
    file: ./.secrets/postgres_db
  postgres_password:
    file: ./.secrets/postgres_password
  postgres_user:
    file: ./.secrets/postgres_user
  nextcloud_admin_user:
    file: ./.secrets/nextcloud_admin_user
  nextcloud_admin_password:
    file: ./.secrets/nextcloud_admin_password

