version: "3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - PUID=${PUID} # optional, your user id
      - PGID=${PGID} # optional, your group id
      - HOMEPAGE_FILE_PIHOLE_KEY=/run/secrets/pihole_api
      - HOMEPAGE_FILE_JELLYFIN_KEY=/run/secrets/jellyfin_api
      - HOMEPAGE_FILE_NGINX_USERNAME=/run/secrets/nginx_username
      - HOMEPAGE_FILE_NGINX_PASSWORD=/run/secrets/nginx_password
    secrets:
      - pihole_api
      - jellyfin_api
      - nginx_username
      - nginx_password
    ports:
      - 3000:3000
    volumes:
      - config:/app/config
      - images:/app/public/images
      - icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    networks:
      pihole_dns_network:               # This is done for so that the container can resolve the DNS
    

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
  images:
    driver: local
    driver_opts:
      type: none
      device: ./images
      o: bind
  icons:
    driver: local
    driver_opts:
      type: none
      device: ./icons
      o: bind

networks:
  # Define custom network so that the container can resolve the DNS
  pihole_dns_network:
    name: "pihole_dns_network"
    external: true


secrets:
  pihole_api:
    file: ./.secrets/pihole_api 
  jellyfin_api:
    file: ./.secrets/jellyfin_api
  nginx_username:
    file: ./.secrets/nginx_username
  nginx_password:
    file: ./.secrets/nginx_password