version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: ${PUID} # optional, your user id
      PGID: ${PGID} # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - config:/app/config
      - images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    networks:
      pihole_dns_network:               # This is done for so that the container can resolve the DNS
    

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
  images:
    driver: local
    driver_opts:
      type: none
      device: ./images
      o: bind

networks:
  # Define custom network so that the container can resolve the DNS
  pihole_dns_network:
    name: "pihole_dns_network"
    external: true

