version: "3.9"
name: media-stack
services:

  ## Default credentials of qBittorrent - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: "unless-stopped"

    networks:               
      media_network:
        ipv4_address: 172.21.200.5
    
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=5080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - data-config:/downloads

    ## Comment/Disable below ports if VPN is enabled
    ports:
      - 5080:5080
      - 6881:6881/tcp
      - 6881:6881/udp
    
    # healthcheck
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5080", "https://google.com"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # radarr:
  #   container_name: radarr
  #   image: lscr.io/linuxserver/radarr:5.3.6
  #   networks:
  #     - media_network
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE}
  #   ports:
  #     - 7878:7878
  #   volumes:
  #     - radarr-config:/config
  #     - torrent-downloads:/downloads
  #   restart: "unless-stopped"

  # sonarr:
  #   image: linuxserver/sonarr:4.0.1-develop
  #   container_name: sonarr
  #   networks:
  #     - media_network 
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - sonarr-config:/config
  #     - torrent-downloads:/downloads
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped

  # prowlarr:
  #   container_name: prowlarr
  #   image: linuxserver/prowlarr:1.13.3
  #   networks:               
  #     - media_network
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - prowlarr-config:/config

  #   # Comment below ports if VPN is enabled.
  #   ports:
  #     - 9696:9696
  #   restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      media_network:
        ipv4_address: 172.21.200.6
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - jellyfin-config:/config
      - data-config:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      # - 7359:7359/udp
      # - 8920:8920


volumes:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
    driver: local
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/jellyfin
      o: bind
  qbittorrent-config:
    driver: local
    driver_opts:
      type: none
      device: ${CONFIG_ROOT}/qbittorrent
      o: bind
  data-config:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_ROOT}
      o: bind
  # cleanmyarr-config:

networks:
  media_network:
    name: "pihole_dns_network"
    external: true

