version: "3"
services:
  proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.21.200.10
    ports:
      - '80:80'
      - '8050:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt


networks:
  proxy:
    name: "pihole_dns_network"
    external: true