---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: github
          href: https://github.com/
          description: Code hosting
    - Stack Overflow:
        - icon: /icons/stackoverflow.svg
          href: https://stackoverflow.com/
          description: Q&A for programmers
    - ChatGPT:
        - icon: openai
          href: https://chat.openai.com/
          description: Chat with GPT-3

- Social:
    - LinkedIn:
        - icon: linkedin
          href: https://linkedin.com/
          description: Professional networking service
    - Twitter:
        - icon: twitter
          href: https://twitter.com/
          description: Microblogging
    - Reddit:
        - icon: reddit
          href: https://reddit.com/
          description: Discussion website
    - Facebook:
        - icon: facebook
          href: https://facebook.com/
          description: Social networking service

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
          description: Video sharing platform
    - Instagram:
        - icon: instagram
          href: https://instagram.com/
          description: Photo and video sharing social networking service
    - Torrentbd:
        - icon: webtorrent
          href: https://torrentbd.net/
          description: Bangladeshi torrent site

- Important:
    - Gmail:
        - icon: gmail
          href: https://mail.google.com/
          description: Email service
    - Google Drive:
        - icon: google-drive
          href: https://drive.google.com/
          description: File storage and synchronization service
    - Moodle:
        - icon: moodle
          href: https://moodle.cse.buet.ac.bd
          description: Learning platform

- Messaging:
    - Messenger:
        - icon: facebook-messenger
          href: https://messenger.com/
          description: Messaging service
    - English-Mattermost:
        - icon: mattermost
          href: https://mattermost-pridesys.eastus.cloudapp.azure.com/
          description: Messaging service
    - Bangla-Mattermost:
        - icon: mattermost
          href: https://mattermost.pridesys.duckdns.org/
          description: Messaging service
    - WhatsApp:
        - icon: whatsapp
          href: https://web.whatsapp.com/
          description: Messaging service