---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

# Title of the homepage
title: Welcome to Homepage


# Background image
background:
  image: images/background-1.jpg
  brightness: 5 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 15 # 0-100

cardBlur: sm 

favicon: images/favicon.ico

theme: dark # dark, light

color: slate # slate, gray, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white

layout:
  # Layout options: row, column
  DNS With Proxy:
    icon: azure-dns
    style: row
    columns: 3
  Media Stack:
    icon: universal-media-server
    style: row
    columns: 3
  Important:
    style: column
  Developer:
    style: column
  Social:
    style: column
  Entertainment:
    style: column

quicklaunch:
  searchDescriptions: true      # Item descriptions are in search context, default false
  hideInternetSearch: false     # Allow searching the internet, default false
  showSearchSuggestions: true   # Show search suggestions, default false
  hideVisitURL: true            # disable the visit URL button, default false

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
