---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

# Title of the homepage
title: Welcome to Homepage


# Background image
background:
  image: images/background-1.jpg
  brightness: 5 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 15 # 0-100

cardBlur: sm 

favicon: images/favicon.ico

theme: dark # dark, light

color: cyan # slate, gray, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white

layout:
  DNS With Proxy:
    icon: azure-dns
    style: row
    columns: 2

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
